### ISSUE TITLE
Page Model Performance

### ISSUE THREAD

**Issue by serdargkaya** [matthiask/feincms3#11]
Hi matt.

Can we change this code. So we only go in if slug is changed or is_active == False.

https://github.com/matthiask/feincms3/blob/master/feincms3/pages.py#L189

Right now we are go in this loop no matter what. But it is too expensive if i have like 500 sub pages.

What do you think?

**Comment by matthiask** [comment]
Oh, I certainly agree it's possible to be smarter about updating descendants.

Checking whether either the `path` (not `slug` because of `static_path`) or `is_active` changed and only saving descendants if they did sounds fine in principle. 

I think we can't just skip updating descendants when `is_active` is `False`, because `path` uniqueness is enforced across all pages, not just those with `is_active=True`

**Comment by serdargkaya** [comment]
Thanks. When can you release a pip package?

**Comment by matthiask** [comment]
You could help by testing the master version locally if that's possible, and report back success or failure? I'd want some real world feedback, not just "the test suite passes" for this change.

If everything looks good I'll happily upload a release during the next few hours.

**Comment by serdargkaya** [comment]
Tested locally. It looks good. No error.
