### ISSUE TITLE
does feincms3 make more sense when extending the model is required

### ISSUE THREAD

**Issue by eskhool** [matthiask/feincms3#3]
Please refer this issue 
[https://github.com/feincms/feincms/issues/648](url)

Does feincms3 make more sense for this use case? Can it be considered 'ready' for production use? Also the benefits of CTE-forest aren't very clear...does postgres CTE make adjacency list perform at par with MPTT for reading nested items?

**Comment by matthiask** [comment]
feincms3 is much more basic than FeinCMS. If you can live with its constraints (Postgres only) then I can only recommend it. You'll have to write more code yourself (or copy it from the [documentation](http://feincms3.readthedocs.io/en/latest/)) but the required code should be quite clear and obvious. Btw, this reminds me that I should really update https://github.com/matthiask/feincms3-example because that was a really good starting point before we switched from mptt to cte.

CTE performs well in our tests, I haven't done any tuning yet for hundreds of pages in a single tree. It's also being used successfully with much bigger trees, here's an example: http://cramer.io/2010/05/30/scaling-threaded-comments-on-django-at-disqus . As an added benefit, you'll never ever experience tree corruption because that's simply not possible when using CTE-forest instead of mptt.

feincms3 is being used in a variety of pages. A few examples: http://www.fcz.ch/de/ , http://www.sos-spielsucht.ch/ , http://www.blindflugstudios.com/  It is production ready (despite the low version number). The only thing I'm unhappy with right now are the `feincms3_pages` template tags, especially `{% menu %}` which we never use ourselves. A better version would be:

```
from collections import defaultdict

from django import template
from django.db.models import Q
from django.utils.translation import get_language

from app.pages.models import Page

register = template.Library()

@register.simple_tag
def menus():
    menus = defaultdict(list)
    pages = Page.objects.filter(
        Q(is_active=True),
        Q(language_code=get_language()),
        ~Q(menu=''),
    ).extra(
        where=['depth BETWEEN 2 AND 3'],
    )
    for page in pages:
        menus[page.menu.replace('-', '_')].append(page)
    return menus
```

**Comment by matthiask** [comment]
Addendum: feincms3-example has been updated :)
